### ISSUE TITLE
1.12.2 spigot端无法正常创建收费门

### ISSUE THREAD

**Issue by 12557584841** [LovesAsuna/Lock#5]
服务端经济插件是 iConomy
然后前置的插件也有装，lock装之后输入lock help有提示说明
但是他就是没办法创建成功，是我操作有问题嘛？我用的是最新发布的那个版本
![N BHFDFXDI1PY4O}23T7I M](https://user-images.githubusercontent.com/64294707/80269789-63e7f480-86e5-11ea-9fab-1ede4b631074.png)

**Comment by LovesAsuna** [comment]
后台有无报错？世界是不是被限制了

**Comment by 12557584841** [comment]
你好，后台没有报错信息。我在world世界创建，但是无法创建成功
config文件我还没有改

**Comment by LovesAsuna** [comment]
1.12.2版本的门类型印象中是不对应的，先输入命令/lock addtype后右键门

**Comment by 12557584841** [comment]
输入指令后他提示我命令不正确

**Comment by LovesAsuna** [comment]
忘了addtype后还有个参数door,后面版本我会删除这个多余参数

**Comment by 12557584841** [comment]
好的，谢谢您。可以用了

**Comment by 12557584841** [comment]
等等，创建成功后无法右键进入

**Comment by LovesAsuna** [comment]
蹲下右键

**Comment by 12557584841** [comment]
好的，谢谢。神话mc玩习惯了，我记得他是有一个再次右键确认的功能好像

**Comment by LovesAsuna** [comment]
这个功能已经完成
